### ISSUE TITLE
{Update Last email Contact}

### ISSUE THREAD

**Issue by JadeKilburn** [NYCDA-Processing/RecruiterSDK#37]
I receive and email every time someone books an audition on our end. 
The email is named 'The Following event has been Changed' and is from whoever books the audition. 
This could be a useful email for someone to receive but I don't think it should be going to me.

**Comment by JadeKilburn** [comment]
It is owned by Recruiter Admin. 
If we could get the notifications from this workflow to go to Nanci, then she can use this information.

**Comment by caseyburden** [comment]
This isn't because of that workflow.  It's an Ellucian recruiter plugin that is sending it because you are listed as the owner of the events.  When I first set events up I was the owner and got this damn email so much that I made a rule in outlook to delete them.  I tried to turn them off already and was told we can't.  Sorry. :-(
