### ISSUE TITLE
inactive contacts that should be "no interest" 

### ISSUE THREAD

**Issue by ncooke** [NYCDA-Processing/RecruiterSDK#4]
For contacts de-activated other than because they were merged--
1. Do we want to activate and change to no interest?
2. If so, what advanced find would help us locate them?
3. Possibly unrelated, is it possible that anyone assigned to Alyssa was de-activated instead of re-assigned.

**Comment by caseyburden** [comment]
1.  Yes, that's a great idea :+1: 
2.  Not so easy to do right now.  There is a way coming in crm 2013, but we won't be there until January.   We'll need to do some research on what marks a record as 'merged' (in CRM2013 there will be a 'master_ID' field.)  So we need an Advanced Find that can go off that.
3.  It is possible that anyone was deactivated and shouldn't be.  Charley used 'deactivate' as his version of 'no interest' for a while and who knows how many times since.  I don't think Alyssa's people fall into that category, mainly because I switched most of her people myself.  But again, nothing is impossible.

**Comment by caseyburden** [comment]
I created a workflow that runs every morning that marks the "merged" inactive files.  I also updated the main "All Inactive Prospects" to show the updates.  This should allow us to quickly get to and sort out the ones that were done incorrectly.
